### ISSUE TITLE
Fullscreen Mode Issue with CT.exe on Linux

### ISSUE THREAD

**Issue by JavaDaVinci** [SWRC-Modding/CT#28]
[steam-16813201761480212480.log](https://github.com/user-attachments/files/17506415/steam-16813201761480212480.log)
Unfortunately, I cannot run the game through CT.exe in fullscreen mode. However, I’ve attached the log file, which I hope will be helpful. The game does run in fullscreen, but only when launched from SWRepublicCommando.exe. I have installed fix 2.12

**Comment by leon-bckl** [comment]
`-fullscreen` is not a command line parameter that is understood by the game.
You can use alt+enter or the `togglefullscreen` console command

**Comment by JavaDaVinci** [comment]
> `-fullscreen` is not a command line parameter that is understood by the game. You can use alt+enter or the `togglefullscreen` console command

Unfortunately, both Alt+Enter and togglefullscreen console command only cause a large spike in frametime without resolving the issue.

**Comment by leon-bckl** [comment]
That's weird then because CT.exe is effectively the same as SWRepublicCommando.exe. All of the graphics/windowing stuff is done in the dlls.
Is it possible that wine/proton does something similar to the NVIDIA drivers on windows where they behave differently based on the name of the exe?
Like for example in order to (inadequately) address the bump mapping issue, the NVIDIA driver converts the unsupported textures to a supported format. But only if the exe is named `SWRepublicCommando.exe`. If you rename it, it will not be recognized as SWRC by the driver and will execute normally resulting in a crash.

You could try renaming the exe to SWRepublicCommando.exe just to see if it changes anything.

But just just the original exe if that works

**Comment by leon-bckl** [comment]
Yes I know. It was just an example on how things are done with the NVIDIA driver which might be similar.
But like I said just use the SWRepublicCommando.exe if that works.

**Comment by JavaDaVinci** [comment]
> Yes I know. It was just an example on how things are done with the NVIDIA driver which might be similar. But like I said just use the SWRepublicCommando.exe if that works.

Ok. Thanks for your time.

**Comment by JavaDaVinci** [comment]
> Yes I know. It was just an example on how things are done with the NVIDIA driver which might be similar. But like I said just use the SWRepublicCommando.exe if that works.

Should I close the the issue or leave it like that ?

**Comment by leon-bckl** [comment]
Can be closed. There's nothing to be done code wise

**Comment by mokMan23** [comment]
> > `-fullscreen` is not a command line parameter that is understood by the game. You can use alt+enter or the `togglefullscreen` console command
> 
> Unfortunately, both Alt+Enter and togglefullscreen console command only cause a large spike in frametime without resolving the issue.

Having the same issue with the GOG version, but only with a newer version of OpenAL that supports EAX emulation. CT.exe still won't run in fullscreen, but the original EXE will by editing my System.ini file. I tried the Vanilla version and it only sutters when I enable EAX, compared to the patch stuttering whether EAX is enabled or not.
